import Nav from "@/components/nav";
import "./globals.css";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
export const metadata = {
  title: "Hello world",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="flex justify-center items-center h-screen">
        <Card className="w-[350px] md:w-[650px]">
          <CardHeader className="mx-4">
            <CardTitle>Profile 🐱</CardTitle>
            <Nav />
            <div className="line h-[1px] bg-slate-600 rounded-full mx-5"></div>
          </CardHeader>
          <CardContent>{children}</CardContent>
          <CardFooter className="">
          </CardFooter>
        </Card>
      </body>
    </html>
  );
}
